on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Test pr-agent-wiki-conf
    steps:
      - name: PR-Agent Wiki Configuration
        uses: idubnori/pr-agent-wiki-conf@develop
        env:
          common_instructions: >-
            - Answer in Japanese.
          pr_reviewer.extra_instructions: >-
            - Additional second priority point: focus on the need for test code additions or changes to the application code changes.
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
