on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Test pr-agent-wiki-conf
    steps:
      - name: PR-Agent Wiki Configuration
        uses: idubnori/pr-agent-wiki-conf@develop
        env:
          common_instructions: >-
            - Please use Japanese in descriptions.
          pr_code_suggestions.extra_instructions: >-
            - Think about the need for changes or additions to the test code and make suggestions.
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      